---
name: intro-cds-website
channels:
  - defaults
dependencies:
  - docutils=0.14
  - jinja2=2.10
  - markdown=3.0.1
  - markupsafe=1.1.0
  - pandoc=2.2.3.2
  - pygments=2.3.1
  - python-dateutil=2.7.5
  - python=3.7.2
  - pytz=2018.9
  - six=1.12.0
  - unidecode=1.0.23
  - pip:
    - ghp-import==0.5.5
    - pelican==3.7.1
    - rpy2==2.9.5
    - typogrify==2.0.7
