Title: Visualization practice
Author: Dr. Glasbrenner
Date: 2019-02-05 23:59
Tags: mini-assignment
Slug: minihw02b-visualization-practice
Summary: A mini-homework to practice using RStudio to run code blocks in RMarkdown files and to create visualizations using ggplot2.
Show_summary: true
Show_link: true

```{r setup, include = FALSE}
icon_html5 <- '<i class="fab fa-html5" data-fa-transform="grow-8"></i>&nbsp;'
icon_github <- '<i class="fab fa-github-alt" data-fa-transform="grow-8"></i>&nbsp;'
assignment_name <- "Mini-homework 2b"
```

[**Due:** February 5, 2019 @ 11:59pm]{.h3}

::: {.no-bullets}
*   [`r icon_html5` Offline, HTML-rendered copy of worksheet (code blocks left unevaluated)][visualization-practice-no-code-preview-html]

*   [`r icon_github` GitHub Classroom repo for **Mini-homework 2b -- Visualization practice**][github-classroom]
:::

## Instructions

::: {.callout .secondary}
[First-time RStudio Server configuration]{.h4}

**Very important!** If this is the first homework assignment that you're completing with RStudio Server, you first will need to follow **all** the directions provided at the link below.
This must be done **before** you start completing homeworks using RStudio Server.
**You only need to do this once.**

:::: {.no-bullets}
*   [`r icon_github` &nbsp; [RStudio Server Configuration repository]{.card-downloads-format}][rstudio-configuration] 
::::
:::

[Obtain the GitHub repository you will use to complete the mini-assignment][github-classroom], which contains a starter file named [visualization_practice.Rmd]{.monospace}.
The demos and exercises you will be completing are written inside [visualization_practice.Rmd]{.monospace}, complete them within the indicated spaces.
When you're ready to submit, follow the directions in the **[How to submit](#how-to-submit)** section below.

## How to submit

To submit your assignment, follow the two steps below.
Your homework will be graded for credit **after** you've completed both steps!

1.  Save, commit, and push your completed R Markdown file so that everything is synchronized to GitHub.
    If you do this right, then you will be able to view your completed file on the GitHub website.

2.  Knit your R Markdown document to the PDF format, export (download) the PDF file from RStudio Server, and then upload it to *`r assignment_name`* posting on Blackboard.

## Cheatsheets

You are encouraged to review and keep the following cheatsheets handy while working on this assignment:

*   [RStudio cheatsheet][rstudio-cheatsheet]

*   [RMarkdown cheatsheet][rmarkdown-cheatsheet]

*   [RMarkdown reference][rmarkdown-reference]

[github-classroom]:                            https://classroom.github.com/a/uZgyzIgD
[rstudio-cheatsheet]:                          /doc/rstudio-ide-cheatsheet.pdf
[rmarkdown-reference]:                         /doc/rmarkdown-reference.pdf
[rmarkdown-cheatsheet]:                        /doc/rmarkdown-cheatsheet.pdf
[rstudio-configuration]:                       https://github.com/mason-fa18-cds-101-dl1/configure-rstudio-server
[visualization-practice-no-code-preview-html]: /doc/minihw02b_visualization_practice_no_code_preview.html
