Title: R Markdown practice
Author: Dr. Glasbrenner
Date: 2019-02-05 23:59
Tags: mini-assignment
Slug: minihw02a-rmarkdown-practice
Summary: A mini-homework on editing R Markdown files and saving to GitHub.
Show_summary: true
Show_link: true

```{r setup, include = FALSE}
icon_pdf <- '<i class="fas fa-file-pdf" data-fa-transform="grow-8"></i>&nbsp;'
icon_html <- '<i class="fab fa-html5" data-fa-transform="grow-8"></i>&nbsp;'
icon_github <- '<i class="fab fa-github-alt" data-fa-transform="grow-8"></i>&nbsp;'
assignment_name <- "Mini-homework 2a"
```

[**Due:** February 5, 2019 @ 11:59pm]{.h3}

::: {.no-bullets}
*   [`r icon_pdf` [minihw02a_rmarkdown_practice_final_output.pdf]{.monospace}][rmarkdown-recreate-pdf]

*   [`r icon_github` GitHub Classroom repo for **Mini-homework 2a -- R Markdown practice**][github-classroom]
:::

## Instructions

::: {.callout .secondary}
[First-time RStudio Server configuration]{.h4}

**Very important!** If this is the first homework assignment that you're completing with RStudio Server, you first will need to follow **all** the directions provided at the link below.
This must be done **before** you start completing homeworks using RStudio Server.
**You only need to do this once.**

:::: {.no-bullets}
*   [`r icon_github` &nbsp; [RStudio Server Configuration repository]{.card-downloads-format}][rstudio-configuration] 
::::
:::

[Obtain the GitHub repository for the activity][github-classroom], which contains a starter file named [rmarkdown_practice.Rmd]{.monospace}.
Use this file and Markdown to re-create the exact formatting of this PDF document [[minihw02a_rmarkdown_practice_final_output.pdf]{.monospace}][rmarkdown-recreate-pdf].
When you're ready to submit, follow the directions in the **[How to submit](#how-to-submit)** section below.

::: {.callout .primary}
[Note]{.h4}

[`r icon_html` [minihw02a_rmarkdown_practice_final_output.html]{.monospace}][rmarkdown-recreate-html] is what you should get if you knit to HTML instead of PDF.
You may find it helpful to compare your knitted HTML with this to make sure you're on the right track.
:::

## How to submit

To submit your assignment, follow the two steps below.
Your homework will be graded for credit **after** you've completed both steps!

1.  Save, commit, and push your completed R Markdown file so that everything is synchronized to GitHub.
    If you do this right, then you will be able to view your completed file on the GitHub website.

2.  Knit your R Markdown document to the PDF format, export (download) the PDF file from RStudio Server, and then upload it to *`r assignment_name`* posting on Blackboard.

## Cheatsheets

You are encouraged to review and keep the following cheatsheets handy while working on this assignment:

*   [RStudio cheatsheet][rstudio-cheatsheet]

*   [RMarkdown cheatsheet][rmarkdown-cheatsheet]

*   [RMarkdown reference][rmarkdown-reference]

[github-classroom]:        https://classroom.github.com/a/yRnkUW7T
[rstudio-cheatsheet]:      /doc/rstudio-IDE-cheatsheet.pdf
[rmarkdown-reference]:     /doc/rmarkdown-reference.pdf
[rmarkdown-cheatsheet]:    /doc/rmarkdown-cheatsheet.pdf
[rstudio-configuration]:   https://github.com/mason-sp19-cds-101-dl1/rstudio-server-initial-configuration
[rmarkdown-recreate-pdf]:  /doc/minihw02a_rmarkdown_practice_final_output.pdf
[rmarkdown-recreate-html]: /doc/minihw02a_rmarkdown_practice_final_output.html
